import * as THREE from '/vendor/three/three.module.js';
import { OrbitControls } from '/vendor/three/controls/OrbitControls.js';

const $ = id => document.getElementById(id);
const els = { canvas:$('terrain'), status:$('status'), runState:$('run-state'), form:$('job-form'), button:$('run-button'),
  image:$('source-image'), imageEmpty:$('image-empty'), terrainEmpty:$('terrain-empty'), info:$('scene-info'), downloads:$('downloads'),
  crs:$('info-crs'), gsd:$('info-gsd'), size:$('info-size'), dtm:$('info-dtm'), datum:$('info-datum'), caption:$('scene-caption'),
  scale:$('vertical-scale'), scaleOut:$('vertical-out'), wire:$('wireframe'), reset:$('reset-view'), pos:$('probe-pos'), height:$('probe-height'), slope:$('probe-slope') };
const renderer = new THREE.WebGLRenderer({canvas:els.canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2));
const scene = new THREE.Scene(); scene.background = new THREE.Color('#091016');
const camera = new THREE.PerspectiveCamera(48,1,.05,1e7); const controls = new OrbitControls(camera,els.canvas); controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xcdefff,0x1b2e22,2.2)); const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(120,250,80);scene.add(sun);
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2(); let terrain=null, active=null, texture=null;
function resize(){const w=els.canvas.clientWidth,h=els.canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(els.canvas);resize();
(function frame(){controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)})();
function setStatus(message){els.status.textContent=message;els.runState.textContent=message}
async function imagePixels(url){const image=await new Promise((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=url});const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0);return {image,pixels:context.getImageData(0,0,image.width,image.height).data,width:image.width,height:image.height}}
async function depthMap(url,range){const decoded=await imagePixels(url),output=new Float32Array(decoded.width*decoded.height);for(let i=0;i<output.length;i++)output[i]=range[0]+((decoded.pixels[i*4]*256+decoded.pixels[i*4+1])/65535)*(range[1]-range[0]);return {...decoded,data:output}}
function resetCamera(){if(!terrain)return;const box=new THREE.Box3().setFromObject(terrain),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),reach=Math.max(size.x,size.z);camera.up.set(0,1,0);controls.target.copy(center);camera.position.set(center.x+reach*.72,center.y+reach*.72,center.z+reach*.72);camera.near=Math.max(.05,reach/1000);camera.far=reach*20;camera.updateProjectionMatrix();controls.update()}
function topCamera(){if(!terrain)return;const box=new THREE.Box3().setFromObject(terrain),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),reach=Math.max(size.x,size.z);camera.up.set(0,0,-1);controls.target.copy(center);camera.position.set(center.x,center.y+reach*1.25,center.z);camera.near=Math.max(.05,reach/1000);camera.far=reach*20;camera.updateProjectionMatrix();controls.update()}
function updateVertical(){if(!terrain)return;terrain.scale.y=Number(els.scale.value);els.scaleOut.textContent=`${Number(els.scale.value).toFixed(2)}×`;resetCamera()}
function disposeTerrain(){if(!terrain)return;scene.remove(terrain);terrain.geometry.dispose();terrain.material.dispose();texture?.dispose();terrain=texture=null}
function buildTerrain(depth,manifest,rgbUrl){const cap=512,step=Math.max(1,Math.ceil(Math.max(depth.width,depth.height)/cap)),width=Math.floor((depth.width-1)/step)+1,height=Math.floor((depth.height-1)/step)+1;
  const positions=new Float32Array(width*height*3),uv=new Float32Array(width*height*2),faces=[];const gsd=manifest.input.gsd_m,base=manifest.artifacts.viewer_depth.range_m[0];
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=y*width+x,sourceY=Math.min(y*step,depth.height-1),sourceX=Math.min(x*step,depth.width-1),elevation=depth.data[sourceY*depth.width+sourceX];positions.set([sourceX*gsd,elevation-base,-sourceY*gsd],i*3);uv.set([x/(width-1),y/(height-1)],i*2)}
  for(let y=0;y<height-1;y++)for(let x=0;x<width-1;x++){const i=y*width+x;faces.push(i,i+1,i+width,i+1,i+width+1,i+width)}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));geometry.setIndex(faces);geometry.computeVertexNormals();
  texture=new THREE.TextureLoader().load(rgbUrl);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({map:texture,roughness:.88,metalness:0,wireframe:els.wire.checked});terrain=new THREE.Mesh(geometry,material);scene.add(terrain);active={depth,manifest,step,width,height,base};updateVertical();els.terrainEmpty.hidden=true}
function fillSceneInfo(manifest,job){els.crs.textContent=manifest.input.crs;els.gsd.textContent=`${manifest.input.gsd_m.toFixed(2)} m per pixel`;els.size.textContent=`${manifest.input.width.toLocaleString()} × ${manifest.input.height.toLocaleString()} pixels`;els.dtm.textContent=manifest.vertical_reference.dtm_source;els.datum.textContent=manifest.vertical_reference.datum;els.info.hidden=false;els.downloads.hidden=false;els.caption.textContent=`${manifest.input.width.toLocaleString()} × ${manifest.input.height.toLocaleString()} satellite pixels on a ${manifest.input.gsd_m.toFixed(2)} m grid. The right panel uses the same image as its texture.`;for(const link of els.downloads.querySelectorAll('[data-artifact]'))link.href=`/api/jobs/${job.id}/artifacts/${link.dataset.artifact}`}
async function show(job){const manifest=await (await fetch(job.manifest)).json(),art=manifest.artifacts,root=`/api/jobs/${job.id}/artifacts/`,cache=`?preview=3`;const [depth] = await Promise.all([depthMap(root+art.viewer_depth.path+cache,art.viewer_depth.range_m)]);disposeTerrain();els.image.src=root+art.viewer_rgb.path+cache;els.image.hidden=false;els.imageEmpty.hidden=true;buildTerrain(depth,manifest,root+art.viewer_rgb.path+cache);fillSceneInfo(manifest,job)}
els.canvas.addEventListener('click',event=>{if(!terrain||!active)return;const rect=els.canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(terrain,false)[0];if(!hit)return;const point=hit.point.clone();point.y/=Number(els.scale.value);const row=Math.max(0,Math.min(active.depth.height-1,Math.round(-point.z/active.manifest.input.gsd_m)));const col=Math.max(0,Math.min(active.depth.width-1,Math.round(point.x/active.manifest.input.gsd_m)));const index=row*active.depth.width+col;const height=active.depth.data[index];const sample=(r,c)=>active.depth.data[Math.max(0,Math.min(active.depth.height-1,r))*active.depth.width+Math.max(0,Math.min(active.depth.width-1,c))];const g=active.manifest.input.gsd_m,dx=(sample(row,col+1)-sample(row,col-1))/(2*g),dy=(sample(row+1,col)-sample(row-1,col))/(2*g);const slope=Math.atan(Math.hypot(dx,dy))*180/Math.PI;const t=active.manifest.input.transform;els.pos.textContent=`E ${((t[0]*col)+t[2]).toFixed(2)}, N ${((t[4]*row)+t[5]).toFixed(2)}`;els.height.textContent=`${height.toFixed(2)} m`;els.slope.textContent=`${slope.toFixed(1)}°`});
els.scale.addEventListener('input',updateVertical);els.wire.addEventListener('change',()=>{if(terrain)terrain.material.wireframe=els.wire.checked});els.reset.addEventListener('click',resetCamera);$('top-view').addEventListener('click',topCamera);
els.form.addEventListener('submit',async event=>{event.preventDefault();els.button.disabled=true;setStatus('Uploading image and ground data…');try{const response=await fetch('/api/jobs',{method:'POST',body:new FormData(els.form)}),job=await response.json();if(!response.ok)throw new Error(job.detail||'Upload failed');while(job.status==='queued'||job.status==='running'){setStatus(job.status==='queued'?'Waiting for the GPU…':'Building the 3D terrain…');await new Promise(resolve=>setTimeout(resolve,700));Object.assign(job,await (await fetch(`/api/jobs/${job.id}`)).json())}if(job.status!=='complete')throw new Error(job.error||'Processing failed');await show(job);setStatus('3D terrain is ready. Compare the two panels or click the terrain to measure it.')}catch(error){console.error(error);setStatus(`Could not create terrain: ${error.message}. The selected files have not been cleared.`)}finally{els.button.disabled=false}});
const existing=new URLSearchParams(location.search).get('job');if(existing){setStatus('Loading saved terrain…');fetch(`/api/jobs/${existing}`).then(response=>response.json()).then(job=>{if(job.status!=='complete')throw new Error(job.error||`Job is ${job.status}`);return show(job)}).then(()=>setStatus('3D terrain is ready. Compare the two panels or click the terrain to measure it.')).catch(error=>setStatus(`Unable to load saved terrain: ${error.message}`))}
