import * as THREE from '/vendor/three/three.module.js';
import { OrbitControls } from '/vendor/three/controls/OrbitControls.js';

const $=id=>document.getElementById(id),els={list:$('scene-list'),source:$('source'),canvas:$('terrain'),loading:$('loading'),name:$('scene-name'),note:$('scene-note'),crs:$('crs'),grid:$('grid'),original:$('original'),pixel:$('pixel'),footprint:$('footprint'),elevation:$('elevation'),coverage:$('coverage'),previous:$('previous'),next:$('next'),reset:$('reset'),scale:$('scale'),scaleOut:$('scale-out'),wire:$('wire')};
const renderer=new THREE.WebGLRenderer({canvas:els.canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const scene=new THREE.Scene();scene.background=new THREE.Color('#070b0f');const camera=new THREE.PerspectiveCamera(48,1,.1,50000),controls=new OrbitControls(camera,els.canvas);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xd8f4ff,0x223326,2.1));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(300,600,150);scene.add(sun);let index=null,current=0,mesh=null,texture=null;
function resize(){const w=els.canvas.clientWidth,h=els.canvas.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(els.canvas);resize();(function frame(){controls.update();renderer.render(scene,camera);requestAnimationFrame(frame)})();
async function decode(url,range){const image=await new Promise((resolve,reject)=>{const item=new Image();item.onload=()=>resolve(item);item.onerror=reject;item.src=url});const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(image,0,0);const pixels=context.getImageData(0,0,image.width,image.height).data,values=new Float32Array(image.width*image.height),span=range[1]-range[0];for(let i=0;i<values.length;i++)values[i]=range[0]+((pixels[i*4]*256+pixels[i*4+1])/65535)*span;return{values,width:image.width,height:image.height}}
function clear(){if(!mesh)return;scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();texture?.dispose();mesh=texture=null}
function resetCamera(){if(!mesh)return;const box=new THREE.Box3().setFromObject(mesh),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),reach=Math.max(size.x,size.z);camera.up.set(0,1,0);controls.target.copy(center);camera.position.set(center.x+reach*.65,center.y+reach*.55,center.z+reach*.7);camera.near=.1;camera.far=reach*20;camera.updateProjectionMatrix();controls.update()}
function topCamera(){if(!mesh)return;const box=new THREE.Box3().setFromObject(mesh),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),reach=Math.max(size.x,size.z);camera.up.set(0,0,-1);controls.target.copy(center);camera.position.set(center.x,center.y+reach*1.25,center.z);camera.near=.1;camera.far=reach*20;camera.updateProjectionMatrix();controls.update()}
function applyScale(){if(!mesh)return;mesh.scale.y=Number(els.scale.value);els.scaleOut.textContent=`${Number(els.scale.value).toFixed(1)}×`;resetCamera()}
function build(data,record,rgbUrl){clear();const w=data.width,h=data.height,positions=new Float32Array(w*h*3),uvs=new Float32Array(w*h*2),faces=[],base=record.elevation_range_m[0],px=record.pixel_size_m;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;positions.set([x*px[0],data.values[i]-base,-y*px[1]],i*3);uvs.set([x/(w-1),y/(h-1)],i*2)}for(let y=0;y<h-1;y++)for(let x=0;x<w-1;x++){const i=y*w+x;faces.push(i,i+1,i+w,i+1,i+w+1,i+w)}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uvs,2));geometry.setIndex(faces);geometry.computeVertexNormals();texture=new THREE.TextureLoader().load(rgbUrl);texture.colorSpace=THREE.SRGBColorSpace;mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({map:texture,roughness:.9,wireframe:els.wire.checked}));scene.add(mesh);applyScale()}
function details(record){els.name.textContent=`${record.id}.tif`;els.note.textContent=record.warning;els.crs.textContent=record.crs;els.grid.textContent=`${record.width} × ${record.height}`;els.original.textContent=`${record.source_width} × ${record.source_height}`;els.pixel.textContent=`${record.pixel_size_m[0].toFixed(2)} × ${record.pixel_size_m[1].toFixed(2)} m`;els.footprint.textContent=`${record.ground_size_m[0].toFixed(0)} × ${record.ground_size_m[1].toFixed(0)} m`;els.elevation.textContent=`${record.elevation_range_m[0].toFixed(1)}–${record.elevation_range_m[1].toFixed(1)} m`;els.coverage.textContent=`${(record.valid_reference_fraction*100).toFixed(1)}%`}
async function select(position){current=(position+index.scenes.length)%index.scenes.length;const record=index.scenes[current],root=`./reference-data/scenes/${record.id}/`;els.loading.hidden=false;document.querySelectorAll('.card').forEach((card,i)=>card.classList.toggle('active',i===current));els.source.src=root+'rgb.jpg';details(record);try{const data=await decode(root+'dsm-rg16.png',record.elevation_range_m);build(data,record,root+'rgb.jpg')}catch(error){els.loading.textContent=`Could not load ${record.id}: ${error.message}`;return}els.loading.hidden=true}
function renderList(){els.list.replaceChildren(...index.scenes.map((record,i)=>{const card=document.createElement('div');card.className='card';card.innerHTML=`<img loading="lazy" src="./reference-data/scenes/${record.id}/rgb.jpg" alt=""><div><b>${record.id}.tif</b><span>${record.elevation_range_m[0].toFixed(0)}–${record.elevation_range_m[1].toFixed(0)} m · ${(record.valid_reference_fraction*100).toFixed(0)}% DSM</span></div>`;card.addEventListener('click',()=>select(i));return card}))}
els.previous.addEventListener('click',()=>select(current-1));els.next.addEventListener('click',()=>select(current+1));els.reset.addEventListener('click',resetCamera);$('top').addEventListener('click',topCamera);els.scale.addEventListener('input',applyScale);els.wire.addEventListener('change',()=>{if(mesh)mesh.material.wireframe=els.wire.checked});
fetch('./reference-data/index.json').then(response=>{if(!response.ok)throw new Error(`index ${response.status}`);return response.json()}).then(value=>{index=value;renderList();return select(0)}).catch(error=>{els.loading.textContent=`Gallery data is unavailable: ${error.message}`});
